### ISSUE TITLE
Article

### ISSUE THREAD

**Issue by mickomicko5573** [gcamfer/Anomaly-ReactionRL#13]
Can you please share the article you based on when building the estimators (especially the simple estimator), thanks.

**Comment by gcamfer** [comment]
I have read a couple of papers to understand the dataset but not significant for the development of estimators.
To learn reinforcement learning I followed the codes/tutorials of Denny Britz [(link)](https://github.com/dennybritz/reinforcement-learning) as well as I read the book of Sutton and Barto. It is possible that the q learning update or the principle of the pseudocode resembles to theirs because of the practice with them. Apart from that for the estimators I have not followed any external paper. 
To better understand the adversarial estimator you can go to the publication [here](https://www.researchgate.net/publication/333169283_Adversarial_environment_reinforcement_learning_algorithm_for_intrusion_detection).

Greetings

**Comment by mickomicko5573** [comment]
Thank you very much.
