### ISSUE TITLE
Environment problem

### ISSUE THREAD

**Issue by lockbro** [gcamfer/Anomaly-ReactionRL#17]
Can you share the specific environment you used? What is the Keras and python version you have used?

**Comment by gcamfer** [comment]
Hi.

I uploaded a [requirements.txt](https://github.com/gcamfer/Anomaly-ReactionRL/blob/master/requirements.txt).
It was developed originaly with tensorflow=1.8.0 and keras==2.2.0 but this tensorflow version is insecure so I've updated now the dependencies.
I tried some scripts and it works but I'm not sure about all. I think it's done fine.

Thanks

**Comment by lockbro** [comment]
Thank you very much！ @gcamfer

**Comment by lockbro** [comment]
What version of python did used? 3.6 or 3.7? Did you used cuda to accelerate?

**Comment by gcamfer** [comment]
Hi!!

I used python 3.5 but is not necesary to be that version. It's compatible with all python 3.x
I also used cuda because I installed tensorflow-gpu but again is no necesary because I use only dense networks and they don't have hardware aceleration. Cuda is really needed if you use CNN or CuDNNLSTM for example.

Greetings
